from mongoengine import Document, StringField, queryset_manager, IntField, DynamicField


class TabelaNutricional(Document):
    description = StringField(required=True)
    category = StringField(required=True)
    humidity_percents = DynamicField(required=True)
    energy_kcal = DynamicField(required=True)
    energy_kj = DynamicField(required=True)
    protein_g = DynamicField(required=True)
    lipidius_g = DynamicField(required=True)
    cholesterol_mg = DynamicField(required=True)
    carbohydrate_g = DynamicField(required=True)
    fiber_g = DynamicField(required=True)
    ashes_g = DynamicField(required=True)
    calcium_mg = DynamicField(required=True)
    magnesium_mg = DynamicField(required=True)
    manganese_mg = DynamicField(required=True)
    phosphorus_mg = DynamicField(required=True)
    iron_mg = DynamicField(required=True)
    sodium_mg = DynamicField(required=True)
    potassium_mg = DynamicField(required=True)
    copper_mg = DynamicField(required=True)
    zinc_mg = DynamicField(required=True)
    retinol_mcg = DynamicField(required=True)
    re_mcg = DynamicField(required=False)
    rae_mcg = DynamicField(required=False)
    tiamina_mg = DynamicField(required=True)
    riboflavin_mg = DynamicField(required=True)
    pyridoxine_mg = DynamicField(required=True)
    niacin_mg = DynamicField(required=True)
    vitaminC_mg = DynamicField(required=False)
    saturated_g = DynamicField(required=True)
    monounsaturated_g = DynamicField(required=True)
    polyunsaturated_g = DynamicField(required=True)
    n12_0_g = DynamicField(required=False)
    n14_0_g = DynamicField(required=True)
    n16_0_g = DynamicField(required=True)
    n18_0_g = DynamicField(required=True)
    n20_0_g = DynamicField(required=True)
    n22_0_g = DynamicField(required=True)
    n24_0_g = DynamicField(required=True)
    n14_1_g = DynamicField(required=False)
    n16_1_g = DynamicField(required=False)
    n18_1_g = DynamicField(required=True)
    n20_1_g = DynamicField(required=True)
    n18_2_n_6_g = DynamicField(required=True)
    n18_3_n_3_g = DynamicField(required=True)
    n20_4_g = DynamicField(required=False)
    n20_5_g = DynamicField(required=False)
    n22_5_g = DynamicField(required=True)
    n22_6_g = DynamicField(required=False)
    n18_1t_g = DynamicField(required=False)
    n18_2t_g = DynamicField(required=False)
    tryptophan_g = DynamicField(required=False)
    threonine_g = DynamicField(required=False)
    isoleucine_g = DynamicField(required=False)
    leucine_g = DynamicField(required=False)
    lysine_g = DynamicField(required=False)
    methionine_g = DynamicField(required=False)
    cystine_g = DynamicField(required=False)
    phenylalanine_g = DynamicField(required=False)
    tyrosine_g = DynamicField(required=False)
    valine_g = DynamicField(required=False)
    arginine_g = DynamicField(required=False)
    histidine_g = DynamicField(required=False)
    alanine_g = DynamicField(required=False)
    aspartic_g = DynamicField(required=False)
    glutamic_g = DynamicField(required=False)
    glycine_g = DynamicField(required=False)
    proline_g = DynamicField(required=False)
    serine_g = DynamicField(required=False)

    def __init__(self, *args, **kwargs):
        super(Document, self).__init__(*args, **kwargs)

    @queryset_manager
    def get_by_description(doc_cls, queryset, description):
        nutriente = queryset(description=str(description)).get()
        return nutriente

    def get_all(self):
        return TabelaNutricional.objects().all()

    meta = {
        'tabela_nutricional': 'tabela_nutricional'
    }
